var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,l){a!=Array.prototype&&a!=Object.prototype&&(a[g]=l.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var g=0;return $jscomp.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var g=a[Symbol.iterator];return g?g.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var g,l=[];!(g=a.next()).done;)l.push(g.value);return l};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
(function(){function a(b){return"string"!==typeof b?[]:[].concat($jscomp.arrayFromIterable(new Set(b.split(" ").filter(Boolean))))}function g(b){return b?"string"===typeof b?document.querySelectorAll(b):b instanceof NodeList?b:"function"===typeof b.addEventListener?[b]:[]:[]}function l(b,a,c,e){var f=e.delegatedTarget,d=e.once,g=function(e){var h=f&&"string"===typeof f?(h=e.target)?"function"===typeof h.matches?h.matches(f):"function"!==typeof h.msMatchesSelector?h.msMatchesSelector(f):!1:!1:!0;h&&
(c.call(b,e,e&&e.detail),d&&b.removeEventListener(a,g))};b.addEventListener(a,g);d||q(b,a,g)}function q(b,a,c){if(b&&a&&c){var d=m.get(b)||{};d[a]=d[a]||[];d[a].push(c);m.set(b,d)}}function r(b,d){var c=m.get(b),e=a(d),f={},h;for(h in c)f.event=h,(e.includes(f.event)||!d)&&c.hasOwnProperty(f.event)&&Array.isArray(c[f.event])&&(c[f.event].forEach(function(a){return function(d){return b.removeEventListener(a.event,d)}}(f)),delete c[f.event]),f={event:f.event};d||m["delete"](b)}function t(b,d,c,e){b.dispatchEvent&&
a(d).forEach(function(a){var d=n.has(a);if(c||!d)a=new CustomEvent(a,Object.assign({detail:c,bubbles:!0},e));else{if(d&&"function"===typeof b[a])return b[a]();a=new Event(a,Object.assign({bubbles:!0},e))}b.dispatchEvent(a)})}function p(b,d,c){for(var e=[],f=2;f<arguments.length;++f)e[f-2]=arguments[f];d=void 0===d?{}:d;if(2>e.length)return b;f=e[0];var g=e[e.length-1],k;3===e.length&&(k=e[1]);var m=a(f);b.forEach(function(a){m.forEach(function(b){return l(a,b,g,Object.assign({},d,{delegatedTarget:k}))})});
return b}var n=new Set,m=new Map,k=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];this.list=new Set;this.add.apply(this,$jscomp.arrayFromIterable(b));return this};k.prototype.add=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var e=this;b.forEach(function(a){a=g(a);Array.prototype.forEach.call(a,function(a){e.list.add(a)},e)},this);return this};k.prototype.on=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];p.apply(null,[this,
{}].concat($jscomp.arrayFromIterable(b)));return this};k.prototype.once=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];p.apply(null,[this,{once:!0}].concat($jscomp.arrayFromIterable(b)));return this};k.prototype.forEach=function(a,d){this.list.forEach(a,void 0===d?this:d);return this};k.prototype.off=function(a){this.forEach(function(b){return r(b,a)});return this};k.prototype.trigger=function(a,d){var b=void 0===d?{}:d,e=b.data,f=b.options;this.forEach(function(b){return t(b,
a,e,f)});return this};var u=function(a){return new k(a)};(function(){for(var a in document)"on"===a.substring(0,2)&&n.add(a.slice(2))})();return window.vent=u})();