var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,k){a!=Array.prototype&&a!=Object.prototype&&(a[g]=k.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var g=0;return $jscomp.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var g=a[Symbol.iterator];return g?g.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var g,k=[];!(g=a.next()).done;)k.push(g.value);return k};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
(function(){function a(b){return"string"!==typeof b?[]:[].concat($jscomp.arrayFromIterable(new Set(b.split(" ").filter(Boolean))))}function g(b){return b?"string"===typeof b?document.querySelectorAll(b):b instanceof NodeList?b:"function"===typeof b.addEventListener?[b]:[]:[]}function k(b,a,c,e){var d=e.delegatedTarget,g=e.once,m=function(f){var e=d&&"string"===typeof d?(e=f.target)?"function"===typeof e.matches?e.matches(d):"function"!==typeof e.msMatchesSelector?e.msMatchesSelector(d):!1:!1:!0;e&&
(c.call(b,f,f&&f.detail),g&&b.removeEventListener(a,m))};b.addEventListener(a,m);g||q(b,a,m)}function q(b,a,c){if(b&&a&&c){var d=l.get(b)||{};d[a]=d[a]||[];d[a].push(c);l.set(b,d)}}function r(b,d){var c=l.get(b),e=a(d),f={},g;for(g in c)f.event=g,(e.includes(f.event)||!d)&&c.hasOwnProperty(f.event)&&Array.isArray(c[f.event])&&(c[f.event].forEach(function(a){return function(d){return b.removeEventListener(a.event,d)}}(f)),delete c[f.event]),f={event:f.event};d||l["delete"](b)}function t(b,d,c,e){b.dispatchEvent&&
a(d).forEach(function(a){a=c||!n.has(a)?new CustomEvent(a,Object.assign({detail:c,bubbles:!0},e)):new Event(a,Object.assign({bubbles:!0},e));b.dispatchEvent(a)})}function p(b,d,c){for(var e=[],f=2;f<arguments.length;++f)e[f-2]=arguments[f];d=void 0===d?{}:d;if(2>e.length)return b;f=e[0];var g=e[e.length-1],h;3===e.length&&(h=e[1]);var l=a(f);b.forEach(function(a){l.forEach(function(b){return k(a,b,g,Object.assign({},d,{delegatedTarget:h}))})});return b}var n=new Set,l=new Map,h=function(a){for(var b=
[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];this.list=new Set;this.add.apply(this,$jscomp.arrayFromIterable(b));return this};h.prototype.add=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var e=this;b.forEach(function(a){a=g(a);Array.prototype.forEach.call(a,function(a){e.list.add(a)},e)},this);return this};h.prototype.on=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];p.apply(null,[this,{}].concat($jscomp.arrayFromIterable(b)));return this};
h.prototype.once=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];p.apply(null,[this,{once:!0}].concat($jscomp.arrayFromIterable(b)));return this};h.prototype.forEach=function(a,d){this.list.forEach(a,void 0===d?this:d);return this};h.prototype.off=function(a){this.forEach(function(b){return r(b,a)});return this};h.prototype.trigger=function(a,d){var b=void 0===d?{}:d,e=b.data,f=b.options;this.forEach(function(b){return t(b,a,e,f)});return this};var u=function(a){return new h(a)};
(function(){for(var a in document)"on"===a.substring(0,2)&&n.add(a.slice(2))})();return window.vent=u})();